curl -L -o minecraft-assets.zip https://github.com/InventivetalentDev/minecraft-assets/zipball/refs/heads/1.21.11
unzip -q minecraft-assets.zip
dir=$(find . -maxdepth 1 -type d -name "InventivetalentDev-*" | head -n 1)
mv "$dir" "1.21.11"
rm -rf minecraft-assets.zip
curl --create-dirs -o lib/jar/lwjgl-glfw.jar https://build.lwjgl.org/stable/bin/lwjgl-glfw/lwjgl-glfw.jar
curl --create-dirs -o lib/jar/lwjgl-opengl.jar https://build.lwjgl.org/stable/bin/lwjgl-opengl/lwjgl-opengl.jar
curl --create-dirs -o lib/jar/lwjgl-stb.jar https://build.lwjgl.org/stable/bin/lwjgl-stb/lwjgl-stb.jar
curl --create-dirs -o lib/jar/lwjgl.jar https://build.lwjgl.org/stable/bin/lwjgl/lwjgl.jar
curl --create-dirs -o lib/natives_linux_arm32/libglfw.so https://build.lwjgl.org/stable/linux/arm32/libglfw.so
curl --create-dirs -o lib/natives_linux_arm32/liblwjgl_opengl.so https://build.lwjgl.org/stable/linux/arm32/liblwjgl_opengl.so
curl --create-dirs -o lib/natives_linux_arm32/liblwjgl_stb.so https://build.lwjgl.org/stable/linux/arm32/liblwjgl_stb.so
curl --create-dirs -o lib/natives_linux_arm32/liblwjgl.so https://build.lwjgl.org/stable/linux/arm32/liblwjgl.so
curl --create-dirs -o lib/natives_linux_arm64/libglfw.so https://build.lwjgl.org/stable/linux/arm64/libglfw.so
curl --create-dirs -o lib/natives_linux_arm64/liblwjgl_opengl.so https://build.lwjgl.org/stable/linux/arm64/liblwjgl_opengl.so
curl --create-dirs -o lib/natives_linux_arm64/liblwjgl_stb.so https://build.lwjgl.org/stable/linux/arm64/liblwjgl_stb.so
curl --create-dirs -o lib/natives_linux_arm64/liblwjgl.so https://build.lwjgl.org/stable/linux/arm64/liblwjgl.so
curl --create-dirs -o lib/natives_linux_mips64/libglfw.so https://build.lwjgl.org/stable/linux/mips64/libglfw.so
curl --create-dirs -o lib/natives_linux_mips64/liblwjgl_opengl.so https://build.lwjgl.org/stable/linux/mips64/liblwjgl_opengl.so
curl --create-dirs -o lib/natives_linux_mips64/liblwjgl_stb.so https://build.lwjgl.org/stable/linux/mips64/liblwjgl_stb.so
curl --create-dirs -o lib/natives_linux_mips64/liblwjgl.so https://build.lwjgl.org/stable/linux/mips64/liblwjgl.so
curl --create-dirs -o lib/natives_linux_ppc64le/libglfw.so https://build.lwjgl.org/stable/linux/ppc64le/libglfw.so
curl --create-dirs -o lib/natives_linux_ppc64le/liblwjgl_opengl.so https://build.lwjgl.org/stable/linux/ppc64le/liblwjgl_opengl.so
curl --create-dirs -o lib/natives_linux_ppc64le/liblwjgl_stb.so https://build.lwjgl.org/stable/linux/ppc64le/liblwjgl_stb.so
curl --create-dirs -o lib/natives_linux_ppc64le/liblwjgl.so https://build.lwjgl.org/stable/linux/ppc64le/liblwjgl.so
curl --create-dirs -o lib/natives_linux_riscv64/libglfw.so https://build.lwjgl.org/stable/linux/riscv64/libglfw.so
curl --create-dirs -o lib/natives_linux_riscv64/liblwjgl_opengl.so https://build.lwjgl.org/stable/linux/riscv64/liblwjgl_opengl.so
curl --create-dirs -o lib/natives_linux_riscv64/liblwjgl_stb.so https://build.lwjgl.org/stable/linux/riscv64/liblwjgl_stb.so
curl --create-dirs -o lib/natives_linux_riscv64/liblwjgl.so https://build.lwjgl.org/stable/linux/riscv64/liblwjgl.so
curl --create-dirs -o lib/natives_linux_x64/libglfw.so https://build.lwjgl.org/stable/linux/x64/libglfw.so
curl --create-dirs -o lib/natives_linux_x64/liblwjgl_opengl.so https://build.lwjgl.org/stable/linux/x64/liblwjgl_opengl.so
curl --create-dirs -o lib/natives_linux_x64/liblwjgl_stb.so https://build.lwjgl.org/stable/linux/x64/liblwjgl_stb.so
curl --create-dirs -o lib/natives_linux_x64/liblwjgl.so https://build.lwjgl.org/stable/linux/x64/liblwjgl.so
curl --create-dirs -o lib/natives_macos_arm64/libglfw.dylib https://build.lwjgl.org/stable/macosx/arm64/libglfw.dylib
curl --create-dirs -o lib/natives_macos_arm64/liblwjgl_opengl.dylib https://build.lwjgl.org/stable/macosx/arm64/liblwjgl_opengl.dylib
curl --create-dirs -o lib/natives_macos_arm64/liblwjgl_stb.dylib https://build.lwjgl.org/stable/macosx/arm64/liblwjgl_stb.dylib
curl --create-dirs -o lib/natives_macos_arm64/liblwjgl.dylib https://build.lwjgl.org/stable/macosx/arm64/liblwjgl.dylib
curl --create-dirs -o lib/natives_macos_x64/libglfw.dylib https://build.lwjgl.org/stable/macosx/x64/libglfw.dylib
curl --create-dirs -o lib/natives_macos_x64/liblwjgl_opengl.dylib https://build.lwjgl.org/stable/macosx/x64/liblwjgl_opengl.dylib
curl --create-dirs -o lib/natives_macos_x64/liblwjgl_stb.dylib https://build.lwjgl.org/stable/macosx/x64/liblwjgl_stb.dylib
curl --create-dirs -o lib/natives_macos_x64/liblwjgl.dylib https://build.lwjgl.org/stable/macosx/x64/liblwjgl.dylib
curl --create-dirs -o lib/natives_windows_arm64/libglfw.dll https://build.lwjgl.org/stable/windowsx/arm64/libglfw.dll
curl --create-dirs -o lib/natives_windows_arm64/liblwjgl_opengl.dll https://build.lwjgl.org/stable/windowsx/arm64/liblwjgl_opengl.dll
curl --create-dirs -o lib/natives_windows_arm64/liblwjgl_stb.dll https://build.lwjgl.org/stable/windowsx/arm64/liblwjgl_stb.dll
curl --create-dirs -o lib/natives_windows_arm64/liblwjgl.dll https://build.lwjgl.org/stable/windowsx/arm64/liblwjgl.dll
curl --create-dirs -o lib/natives_windows_x64/libglfw.dll https://build.lwjgl.org/stable/windowsx/x64/libglfw.dll
curl --create-dirs -o lib/natives_windows_x64/liblwjgl_opengl.dll https://build.lwjgl.org/stable/windowsx/x64/liblwjgl_opengl.dll
curl --create-dirs -o lib/natives_windows_x64/liblwjgl_stb.dll https://build.lwjgl.org/stable/windowsx/x64/liblwjgl_stb.dll
curl --create-dirs -o lib/natives_windows_x64/liblwjgl.dll https://build.lwjgl.org/stable/windowsx/x64/liblwjgl.dll
curl --create-dirs -o lib/natives_windows_x86/libglfw.dll https://build.lwjgl.org/stable/windowsx/x86/libglfw.dll
curl --create-dirs -o lib/natives_windows_x86/liblwjgl_opengl.dll https://build.lwjgl.org/stable/windowsx/x86/liblwjgl_opengl.dll
curl --create-dirs -o lib/natives_windows_x86/liblwjgl_stb.dll https://build.lwjgl.org/stable/windowsx/x86/liblwjgl_stb.dll
curl --create-dirs -o lib/natives_windows_x86/liblwjgl.dll https://build.lwjgl.org/stable/windowsx/x86/liblwjgl.dll
curl --create-dirs -o lib/jar/org.jar https://maven.jans.io/maven/org/json/json/20231013/json-20231013.jar